// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksflmwteozbssvsbyuue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZmxtd3Rlb3pic3N2c2J5dXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDQ4MzcsImV4cCI6MjA2NTg4MDgzN30.n1Q-Uh-bkM1DsIF4akj0yTulAn8pu7EYCspa5Kce_GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);